name: Build and Push Frontend Docker Image to Docker Hub

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      version:
        description: 'Version for Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          amitgautam67/track4u_frontend:${{ github.event.inputs.version }}
          amitgautam67/track4u_frontend:latest



