# name: Build and Push Frontend Docker Image to Docker Hub

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#     - name: Build Docker Image
#       run: docker build -t amitgautam67/track4u_frontend .

#     - name: Push Docker Image to Docker Hub
#       run: docker push amitgautam67/track4u_frontend:V.1.0.0

name: Build and Push Frontend Docker Image to Docker Hub

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Determine Tag
        id: determine_tag
        run: |
          if [[ $GITHUB_REF == 'refs/tags/v1.0.0' ]]; then
            echo "v1.0.0"
          else
            echo "latest"  # Default tag for non-tagged pushes
          fi
        shell: bash

      - name: Build Docker Image
        run: docker build -t amitgautam67/track4u_frontend:${{ steps.determine_tag.outputs.tag }} .

      - name: Push Docker Image to Docker Hub
        run: docker push amitgautam67/track4u_frontend:${{ steps.determine_tag.outputs.tag }}

