# name: Build and Push Frontend Docker Image to Docker Hub

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Login to Docker Hub
#       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#     - name: Build Docker Image
#       run: docker build -t amitgautam67/track4u_frontend .

#     - name: Push Docker Image to Docker Hub
#       run: docker push amitgautam67/track4u_frontend:latest
name: Build and Push Frontend Docker Image to Docker Hub

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
       - name: Build and Push Docker Image
  uses: docker/build-push-action@v2
  with:
    context: .
    push: true
    tags: |
      amitgautam67/track4u_frontend:${{ github.event.inputs.version }}
      amitgautam67/track4u_frontend:latest


